### ISSUE TITLE
Better composer support

### ISSUE THREAD

**Issue by jensscherbl** [gabordemooij/stamp#11]
Package is missing from packagist.org. Also, release tags are missing since 2.1.0, so composer can't find the proper version when adding the repository directly.

**Comment by gabordemooij** [comment]
Sorry, I never use composer myself, so I rely on others to 'tell me what they want'. I will add the missing tags asap.

**Comment by jensscherbl** [comment]
Publishing on Packagist would be preferable, but I guess tags are necessary either way. Great package, by the way, thanks a lot.
