### ISSUE TITLE
Add the unit test with PHPUnit

### ISSUE THREAD

**Issue by peter279k** [gabordemooij/stamp#15]
As title, I think we can write the unit tests with PHPUnit at this time.
I think this can be more proper than using the customized tests.

Thanks.

**Comment by gabordemooij** [comment]
Fuck PHPUnit.

**Comment by gabordemooij** [comment]
Sorry - lost my temper. But seriously no. How sad is the world that we need a 'Unit test framework' to do something that in essence is no more than '==='?

**Comment by peter279k** [comment]
@gabordemooij, thank you for your reply.

Firstly, this is the "suggestion" about this and it's not an required work to do this.

If not, just close that and don't be angry.
